#+ endpoint: http://ecaickathon-api.tech:3030/default/query
#+ method: GET
#+ summary: Number of triples per graph
#+ tags: 
#+   - metadata 


SELECT ?subject ?predicate ?object
WHERE {
  ?subject ?predicate ?object
}
LIMIT 25
